(ns virtual-keyboard-example.main
  (:require
   ["package:flutter/material.dart" :as m]
   ["package:flutter/foundation.dart" :refer [kIsWeb]]
   [cljd.flutter :as f]
   [virtual-keyboard-example.basic :as example-basic]
   [virtual-keyboard.options :as options]
  ;;  [virtual-keyboard-example.emoji :as example-emoji]
   [ime-core.remote-api :as remote]
   [ime-core.fst-engine :as fst-engine]
   [ime-core.next-word :as next-word]))

(defn ^:async main []
  (m.WidgetsFlutterBinding/ensureInitialized)

  (remote/set-config! {:base-url options/base-url
                       :candidate-api-path options/candidate-api-path
                       :next-word-api-path options/next-word-api-path})

  (when-not kIsWeb
    (await (next-word/ensure-loaded))
    (await (fst-engine/ensure-loaded))) 
  
  (f/run (m/MaterialApp
    .title "Welcome to Flutter"
    .themeMode m.ThemeMode/system
    .theme (m/ThemeData .primarySwatch m.Colors/blue
                        .brightness m/Brightness.dark
                        .fontFamily "OyunQaganTig")
    .home
    ;; (example-emoji/basic)
    ;; (example-styled/styled)
    ;; (m/Scaffold
    ;; ;;  .appBar (m/AppBar
    ;; ;;           .title (m/Text "Mongolian Search Bar"))
    ;;  .body
    ;;  (m/Center
    ;;   .child (mgl/MongolText
    ;;           " ᠳᠠᠶᠠᠭᠠᠷ ᠰᠠᠶ᠋ᠢᠨ ᠪᠠᠶ᠋ᠢᠨ᠎ᠠ ᠊ᠤᠤ?"
    ;;           .style (m/TextStyle
    ;;                   .color m.Colors/blue
    ;;                   ;; .fontFamily "MongolianBaiZheng"
    ;;                   .fontSize 32.0))))
    (example-basic/basic)
    .debugShowCheckedModeBanner false)))
