(ns virtual-keyboard.keyboard-builder
  (:require
   [virtual-keyboard.keyboard-key :as keyboard-key]
   [virtual-keyboard.keyboard-action :as keyboard-action]
   [ime-core.linguistics :as linguistics]
   [clojure.string :as str]))

(def mn-index-layout
  [["q" "w" "e" "r" "t" "y" "u" "i" "o" "p"]
   ["a" "s" "d" "f" "g" "h" "j" "k" "l" "ng"]
   ["-" "z" "x" "c" "v" "b" "n" "m" "_"]])

(defn key-map-builder
  [{m :row-index n :item-index
    items-count :items-count
    rows-count :rows-count
    custom-fns :custom-fns}
   item]
  (cond
    ;; (= :empty item)
    ;; nil

    (or
     (some #{item} ["᠂" "᠃"])
     (and
      (string? item)
      ;; Use the pure function from our core linguistics engine
      (linguistics/is-mongolian? (int (first item)))))
    (keyboard-key/key-widget
     {:text (as-> item m
              (subs m 0 1))
      :key-type :string
      :id (get-in mn-index-layout [m n])
      :is-rotated true
      :display item}
     items-count
     rows-count
     custom-fns)

    (string? item)
    (keyboard-key/key-widget
     {:key-type :string
      :caps-text (str/upper-case item)
      :text item
      :is-rotated false}
     items-count
     rows-count
     custom-fns)

    :else
    (keyboard-action/action-widget
     {:key-type :action
      :action item
      :is-rotated false}
     items-count rows-count custom-fns)))

(defn keyboard-layout-builder [layout custom-fns]
  (map-indexed
   (fn [m row]
     (map-indexed
      (fn [n itm]
        (key-map-builder
         {:row-index m :item-index n
          :items-count (count (nth layout m))
          :rows-count (count layout)
          :custom-fns custom-fns}
         (get-in layout [m n])))
      row))
   layout))