(ns virtual-keyboard.keyboard-rows
  (:require
   ["package:flutter/material.dart" :as m]
   [cljd.flutter :as f]
   [virtual-keyboard.options :as options]))

(declare keyboard-row-keys)

(defn keyboard-rows [rows]
  (f/widget
   :context ctx
   :get {:value-of [:info]}
   (let [width (-> m/MediaQuery (.of ctx) .-size .-width)]
     (m/Container
      .height (options/keyboard-height info (count rows))
      .width width
      .child (m/Column
              .mainAxisSize (.min m/MainAxisSize)
              .mainAxisAlignment (.center m/MainAxisAlignment)
              .crossAxisAlignment (.center m/CrossAxisAlignment)
              .children (keyboard-row-keys info rows))))))

(defn keyboard-row-keys [info items]
  (doall
   (map
    (fn [x]
      (f/widget
       (m/Material
        .color m.Colors/transparent)
       .child
       (m/Padding
        .padding
        (.symmetric
         m/EdgeInsets
         .vertical (:keyboard/row-vertical-padding info)
         .horizontal 0))
       .child
       (m/Row
        .mainAxisAlignment (.start m/MainAxisAlignment)
        .crossAxisAlignment (.center m/CrossAxisAlignment)
        .children x)))

    items)))
