(ns virtual-keyboard.utils
  (:require
   ["package:flutter/material.dart" :as m]
   ["package:mongol/mongol.dart" :as mgl]
   [cljd.flutter.alpha2 :as f]))

(defn get-key-button-size [ctx]
  (let [screen-width (-> m/MediaQuery (.of ctx) .-size .-width)
        screen-height (-> m/MediaQuery (.of ctx) .-size .-height)
        width (* screen-width (if (> screen-width 350) 0.084 0.082))
        height (* screen-height (if (> screen-height 800) 0.059 0.07))]
    [width height]))